[package]
name = "disk-usage"
version = "0.1.0"
edition = "2021"

[dependencies]
bytesize = "1.3.0"
clap = { version = "4.5.14", features = ["derive"] }
procfs = "0.16.0"
sysinfo = "0.31.2"
tabled = { version = "0.16.0", features = ["ansi"] }

[profile.release]
lto = "fat"
strip = true
